[book]
authors = ["Tianjia Zhang"]
language = "en"
multilingual = false
src = "src"
title = "商用密码技术最佳实践白皮书"

[build]
build-dir = "docs"

[preprocessor.template]

[output.html]
no-section-label = true
additional-css = ["custom.css"]

[output.html.fold]
enable = true
